version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    command: python app.py

  model_service:
    build:
      context: ./model_service
    ports:
      - "5001:5000"
    volumes:
      - ./model_service:/app
    command: python model_server.py
